//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefTheme {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NotifyMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotifyMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RefTheme.NotifyMessages", typeof(NotifyMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program must be run as administrator!.
        /// </summary>
        internal static string exceptionAdminTask {
            get {
                return ResourceManager.GetString("exceptionAdminTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version detected (.
        /// </summary>
        internal static string newVerNot {
            get {
                return ResourceManager.GetString("newVerNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can update the program by clicking the update check button.
        /// </summary>
        internal static string notifyIcMessage {
            get {
                return ResourceManager.GetString("notifyIcMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change settings..
        /// </summary>
        internal static string notifyIconToolText {
            get {
                return ResourceManager.GetString("notifyIconToolText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the latest version!.
        /// </summary>
        internal static string notifyLastestV {
            get {
                return ResourceManager.GetString("notifyLastestV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application will be automatically updated and restarted..
        /// </summary>
        internal static string notifyMes2 {
            get {
                return ResourceManager.GetString("notifyMes2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added:.
        /// </summary>
        internal static string notifyMes3 {
            get {
                return ResourceManager.GetString("notifyMes3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will create an automatic task to update the theme after unlocking your user. Continue?.
        /// </summary>
        internal static string notifyTaskCreating {
            get {
                return ResourceManager.GetString("notifyTaskCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The task to automatically update the theme has already been created. Continue?.
        /// </summary>
        internal static string notifyTastAlready {
            get {
                return ResourceManager.GetString("notifyTastAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task successfully added! Now after login to the system, the theme will be updated automatically.
        /// </summary>
        internal static string notifyTastSuccess {
            get {
                return ResourceManager.GetString("notifyTastSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select theme file.
        /// </summary>
        internal static string titleOFD {
            get {
                return ResourceManager.GetString("titleOFD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable auto update theme when starts.
        /// </summary>
        internal static string tooltipToggle {
            get {
                return ResourceManager.GetString("tooltipToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string versionS {
            get {
                return ResourceManager.GetString("versionS", resourceCulture);
            }
        }
    }
}
