//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefTheme {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NotifyMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotifyMessages() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RefTheme.NotifyMessages", typeof(NotifyMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The program must be run as administrator!.
        /// </summary>
        internal static string exceptionAdminTask {
            get {
                return ResourceManager.GetString("exceptionAdminTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New version detected (.
        /// </summary>
        internal static string newVerNot {
            get {
                return ResourceManager.GetString("newVerNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You can update the program by clicking the update check button.
        /// </summary>
        internal static string notifyIcMessage {
            get {
                return ResourceManager.GetString("notifyIcMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change settings..
        /// </summary>
        internal static string notifyIconToolText {
            get {
                return ResourceManager.GetString("notifyIconToolText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have the latest version!.
        /// </summary>
        internal static string notifyLastestV {
            get {
                return ResourceManager.GetString("notifyLastestV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The application will be automatically updated and restarted..
        /// </summary>
        internal static string notifyMes2 {
            get {
                return ResourceManager.GetString("notifyMes2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Added:.
        /// </summary>
        internal static string notifyMes3 {
            get {
                return ResourceManager.GetString("notifyMes3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This will create an automatic task to update the theme after unlocking your user. Continue?.
        /// </summary>
        internal static string notifyTaskCreating {
            get {
                return ResourceManager.GetString("notifyTaskCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The task to automatically update the theme has already been created. Continue?.
        /// </summary>
        internal static string notifyTastAlready {
            get {
                return ResourceManager.GetString("notifyTastAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Task successfully added! Now after login to the system, the theme will be updated automatically.
        /// </summary>
        internal static string notifyTastSuccess {
            get {
                return ResourceManager.GetString("notifyTastSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select theme file.
        /// </summary>
        internal static string titleOFD {
            get {
                return ResourceManager.GetString("titleOFD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable auto update theme when starts.
        /// </summary>
        internal static string tooltipToggle {
            get {
                return ResourceManager.GetString("tooltipToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Version:.
        /// </summary>
        internal static string versionS {
            get {
                return ResourceManager.GetString("versionS", resourceCulture);
            }
        }
    }
}
